version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./01-mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:6.7.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: always

  telegraf:
    image: telegraf:1.14
    container_name: telegraf
    volumes:
      - ./03-telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - mosquitto
      - influxdb
    restart: always

  pylarexx:
    build: ./04-pylarexx
    image: ixs/pylarexx
    container_name: pylarexx
    privileged: true
    volumes:
      - ./04-pylarexx/pylarexx.yaml:/app/pylarexx.yaml
      - /dev/bus/usb:/dev/bus/usb
    depends_on:
      - influxdb
    restart: always

  knxbridge:
    build: ./02-knxbridge
    image: ixs/knxbridge
    container_name: knxbridge
    depends_on:
      - influxdb
    restart: always
    network_mode: host
